<?php

namespace nya0203\math;

use pocketmine\math\Vector3;

class Vector4 {
    public function __construct(public Vector3 $vector3, public int $time) {
    }

    public static function parseVector4(Vector3 $vector3, int $time): Vector4 {
        return new Vector4($vector3, $time);
    }

    public function getTime(): int {
        return $this->time;
    }

    public function replaceVector3(Vector3 $vector3): Vector4 {
        return new Vector4($vector3, $this->time);
    }

    public function setTime(int $time): Vector4 {
        return new Vector4($this->vector3, $time);
    }

    public function addTime(int $time): Vector4 {
        return new Vector4($this->vector3, $this->time + $time);
    }

    public function subTime(int $time): Vector4 {
        return new Vector4($this->vector3, $this->time - $time);
    }

    public function toVector3(): Vector3 {
        return new Vector3($this->vector3->getX(), $this->vector3->getY(), $this->vector3->getZ());
    }

    public function equals(Vector4 $vector4): bool {
        return $this->vector3->equals($vector4->toVector3()) && $this->time === $vector4->getTime(); // TODO: Change the autogenerated stub
    }
}